version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_DB: memes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    restart: always
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
